name: Automated tests
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm i && npm run build

      - name: Running CRA test
        run: |
          npm i -g serve
          serve -s build -l 8000 &
          npm run e2e:ci
